### ISSUE TITLE
Обзор кода

### ISSUE THREAD

**Issue by jafarsirojov** [JAbduvohidov/priority-queue#1]
@jafarsirojov
Нужно было написать три функции теста:
одну для пустой очереди;
одну для очереди с одним элементом;
одну для очереди с несколькими элементами.

**Comment by JAbduvohidov** [comment]
Jafar засунь свой issue куда по дальше подальше.
Препод сказал так! Я сделал так!

**Comment by jafarsirojov** [comment]
У тебя первый тест работает не с пустой очередью. Третий тест работает с очередью из одного элемента. Это как минимум.
